/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Coneccion.Coneccion;
import Controlador.Controlador_Ruta;
import Controlador.Controlador_Tanqueo;
import Controlador.Controlador_Vehiculo;
import Modelo.Tanqueo;
import static Vista.Frame_Tanqueo.id_usuario;
import static Vista.Frame_Tanqueo.id_vehiculo;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.DateFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Arice
 */
public final class Frame_Reportes extends javax.swing.JFrame {
    static String correo;
    static String vehiculo;
    DefaultTableModel dt=new DefaultTableModel();
    Controlador_Tanqueo controller = new Controlador_Tanqueo();
    Controlador_Vehiculo controlador=new Controlador_Vehiculo();
    public static String tipo;
    public static String id_usuario;
    public static String id_vehiculo;
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    Calendar  fecha_actual=new GregorianCalendar();
    DateFormat formateador= new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE", new Locale("es", "ES"));
    DateFormatSymbols dfs = new DateFormatSymbols(new Locale("es"));
    SimpleDateFormat formatoHora = new SimpleDateFormat("hh:mm a");
    /**
     * Creates new form Frame_Reportes
     */
    public Frame_Reportes() {
        initComponents();
        dt =(DefaultTableModel)jTablaReporte.getModel();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        this.setExtendedState(6);
        showLineChart();
        listarTanqueos(); 
    }
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Frame.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        cbResumen = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Logout = new Vista.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelReporte = new Vista.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound9 = new Vista.PanelRound();
        jRuta = new javax.swing.JLabel();
        jVehiculo = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTanqueo = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jInicio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaReporte = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        panelLineChart = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setPreferredSize(new java.awt.Dimension(700, 300));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbResumen.setEditable(true);
        cbResumen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tanqueo", "Ahorro vs Gastos", "Consumo por ruta", "Ahorro" }));
        cbResumen.setToolTipText("");
        cbResumen.setBorder(null);
        cbResumen.setFocusable(false);
        cbResumen.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbResumenItemStateChanged(evt);
            }
        });
        cbResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbResumenActionPerformed(evt);
            }
        });
        jPanel2.add(cbResumen, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 360, -1, -1));

        jPanel3.setBackground(new java.awt.Color(26, 25, 25));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 35, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 10.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Logout.setBackground(new java.awt.Color(47, 47, 47));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setRoundBottomLeft(10);
        Logout.setRoundBottomRight(10);
        Logout.setRoundTopLeft(10);
        Logout.setRoundTopRight(10);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 15, 20, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/placeholder.png"))); // NOI18N
        Logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel3.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 150, 50));

        panelReporte.setBackground(new java.awt.Color(0, 106, 255));
        panelReporte.setForeground(new java.awt.Color(255, 255, 255));
        panelReporte.setRoundBottomLeft(10);
        panelReporte.setRoundBottomRight(10);
        panelReporte.setRoundTopLeft(10);
        panelReporte.setRoundTopRight(10);
        panelReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelReporteMouseClicked(evt);
            }
        });
        panelReporte.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Reportes");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelReporte.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 13, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Report1.png"))); // NOI18N
        panelReporte.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 13, -1, -1));

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setForeground(new java.awt.Color(255, 255, 255));
        panelRound9.setRoundBottomLeft(5);
        panelRound9.setRoundBottomRight(5);
        panelRound9.setRoundTopLeft(5);
        panelRound9.setRoundTopRight(5);
        panelRound9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelReporte.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 5, 40));

        jPanel3.add(panelReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 450, 180, 50));

        jRuta.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jRuta.setForeground(new java.awt.Color(255, 255, 255));
        jRuta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu (4).png"))); // NOI18N
        jRuta.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jRuta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRuta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRutaMouseClicked(evt);
            }
        });
        jPanel3.add(jRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 180, -1));

        jVehiculo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        jVehiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu (1).png"))); // NOI18N
        jVehiculo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jVehiculo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jVehiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jVehiculoMouseClicked(evt);
            }
        });
        jPanel3.add(jVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, 180, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Header.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 330, 180, -1));

        jTanqueo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTanqueo.setForeground(new java.awt.Color(255, 255, 255));
        jTanqueo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu (2).png"))); // NOI18N
        jTanqueo.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jTanqueo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTanqueo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTanqueoMouseClicked(evt);
            }
        });
        jPanel3.add(jTanqueo, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 390, 180, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Split line.png"))); // NOI18N
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, -1));

        jInicio.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jInicio.setForeground(new java.awt.Color(255, 255, 255));
        jInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        jInicio.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jInicioMouseClicked(evt);
            }
        });
        jPanel3.add(jInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 180, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTablaReporte.setAutoCreateRowSorter(true);
        jTablaReporte.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTablaReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Vehiculo", "Lugar", "Cantidad", "Monto", "Fecha"
            }
        ));
        jTablaReporte.setFillsViewportHeight(true);
        jTablaReporte.setFocusCycleRoot(true);
        jTablaReporte.setGridColor(new java.awt.Color(255, 255, 255));
        jTablaReporte.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jTablaReporte.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTablaReporte);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 1030, 220));

        jLabel35.setText("Historial");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, -1, -1));

        jLabel36.setText("Resumen");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 360, -1, -1));

        panelLineChart.setBackground(new java.awt.Color(255, 255, 255));
        panelLineChart.setLayout(new java.awt.BorderLayout());
        jPanel2.add(panelLineChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 1020, 250));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Graph3.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Live Car Status2.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 1110, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTanqueoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTanqueoMouseClicked
        this.setVisible(false);
        Frame_Tanqueo tanqueo = new  Frame_Tanqueo();
        tanqueo.setLocationRelativeTo(null);
        tanqueo.setVisible(true);
    }//GEN-LAST:event_jTanqueoMouseClicked

    private void panelReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelReporteMouseClicked
        this.setVisible(false);
        Frame_Reportes reporte = new  Frame_Reportes();
        reporte.setLocationRelativeTo(null);
        reporte.setVisible(true);
    }//GEN-LAST:event_panelReporteMouseClicked

    private void jRutaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRutaMouseClicked
        this.setVisible(false);
        Frame_Ruta ruta = new  Frame_Ruta();
        ruta.setLocationRelativeTo(null);
        ruta.setVisible(true);
    }//GEN-LAST:event_jRutaMouseClicked

    private void jVehiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jVehiculoMouseClicked
       this.setVisible(false);
        Frame_Vehiculo vehiculo = new  Frame_Vehiculo();
        vehiculo.setLocationRelativeTo(null);
        vehiculo.setVisible(true);
    }//GEN-LAST:event_jVehiculoMouseClicked

    private void jInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jInicioMouseClicked
        this.setVisible(false);
        Frame_Inicio inicio = new  Frame_Inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_jInicioMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        Frame_Inicio inicio = new  Frame_Inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cbResumenItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbResumenItemStateChanged
        
    }//GEN-LAST:event_cbResumenItemStateChanged

    private void cbResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbResumenActionPerformed
        switch (cbResumen.getSelectedIndex()) {
            case 0:
                showPieChart();
                break;
            case 1:
                 showPiePanel();
                break;
            case 2:
                showLineChart1();
                break;
            case 3:
                showLineChart();
                break;
            default:
                throw new AssertionError();
        }
    
    }//GEN-LAST:event_cbResumenActionPerformed

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
       this.setVisible(false);
        Frame_usuario usu = new  Frame_usuario();
        usu.setLocationRelativeTo(null);
        usu.setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked
    private void listarTanqueos() {         
        dt.setRowCount(0);
        for(Tanqueo tanqueo:controller.listarTanqueos(id_usuario, id_vehiculo)){
            Object v[]={
                tanqueo.getCodTanqueo(), 
                tanqueo.getVehiculo().getCodVehiculo(), 
                tanqueo.getLugar(), 
                tanqueo.getCantLlenada(), 
                tanqueo.getPagoTotal(),  
                tanqueo.getFecha()};
            dt.addRow(v);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Reportes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Reportes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.PanelRound Logout;
    private javax.swing.JComboBox<String> cbResumen;
    private javax.swing.JLabel jInicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jRuta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaReporte;
    private javax.swing.JLabel jTanqueo;
    private javax.swing.JLabel jVehiculo;
    private javax.swing.JPanel panelLineChart;
    private Vista.PanelRound panelReporte;
    private Vista.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
    public void showPiePanel() {        
        
        DefaultPieDataset barDataset = new DefaultPieDataset();
        barDataset.setValue("Ahorro", controller.ahorroanio(id_usuario));
        barDataset.setValue("Gasto", controller.ahorrogasto(id_usuario));
        //create chart
        JFreeChart piechart =ChartFactory.createPieChart("Ahorro vs Gastos",barDataset, true, true, false);
        
        PiePlot piePlot =(PiePlot) piechart.getPlot();
     //changing pie chart blocks colors
        piePlot.setSectionPaint("Ahorro", new Color (10,204, 204));
        piePlot.setSectionPaint ("Gasto", new Color(102, 255, 102));
        piePlot.setBackgroundPaint (Color. white);
        piePlot.setOutlinePaint(Color. white);
        piePlot.setLabelOutlinePaint(Color. white);
        piePlot.setBaseSectionPaint(Color. white);
       //create chartPanel to display chart (gcaph)
       ChartPanel barChartPanel = new ChartPanel (piechart);
       panelLineChart.removeAll();
       panelLineChart.add(barChartPanel, BorderLayout.CENTER);
       panelLineChart.validate();

    }
    
    public void showPieChart(){
        Coneccion c = new Coneccion();
        Connection con = c.getConectar();
        ResultSet rs = null;
        PreparedStatement ps= null;
        try {
            ps=con.prepareStatement("SELECT t.lugar_llenado, COUNT(*) AS repeticiones FROM Tanqueo t INNER JOIN Ruta r ON r.id_ruta = t.id_ruta WHERE r.id_usuario =? AND t.lugar_llenado <>'no' GROUP BY t.lugar_llenado HAVING COUNT(*) >= 1ORDER BY repeticiones DESC");
            ps.setString(1, id_usuario);
            rs = ps.executeQuery();
            DefaultPieDataset barDataset = new DefaultPieDataset();
            while(rs.next()){
                barDataset.setValue(rs.getString(1), rs.getInt(2));
            }
             //create chart
        JFreeChart piechart =ChartFactory.createPieChart("Tanqueo por grifo",barDataset, true, true, false);
        PiePlot piePlot =(PiePlot) piechart.getPlot();
     //changing pie chart blocks colors
        piePlot.setBackgroundPaint (Color. white);
        piePlot.setOutlinePaint(Color. white);
        piePlot.setLabelOutlinePaint(Color. white);
        piePlot.setBaseSectionPaint(Color. white);
       //create chartPanel to display chart (gcaph)
       ChartPanel barChartPanel = new ChartPanel (piechart);
       panelLineChart.removeAll();
       panelLineChart.add(barChartPanel, BorderLayout.CENTER);
       panelLineChart.validate();
        } catch (Exception e) {
            System.out.println("Error al obtener los grifos: "+e.getMessage());
        }        
    }
    
    public void showLineChart(){
        Coneccion c = new Coneccion();
        Connection con = c.getConectar();
        ResultSet rs = null;
        PreparedStatement ps= null;
        try {
            ps=con.prepareStatement("SELECT ISNULL(SUM(pago_total) - LAG(SUM(pago_total)) OVER (ORDER BY MONTH(fecha_llenado)), 0) AS ahorro, CASE WHEN MONTH(fecha_llenado) = 1 THEN 'Enero' WHEN MONTH(fecha_llenado) = 2 THEN 'Febrero' WHEN MONTH(fecha_llenado) = 3 THEN 'Marzo' WHEN MONTH(fecha_llenado) = 4 THEN 'Abril' WHEN MONTH(fecha_llenado) = 5 THEN 'Mayo' WHEN MONTH(fecha_llenado) = 6 THEN 'Junio' WHEN MONTH(fecha_llenado) = 7 THEN 'Julio' WHEN MONTH(fecha_llenado) = 8 THEN 'Agosto' WHEN MONTH(fecha_llenado) = 9 THEN 'Septiembre' WHEN MONTH(fecha_llenado) = 10 THEN 'Octubre' WHEN MONTH(fecha_llenado) = 11 THEN 'Noviembre' WHEN MONTH(fecha_llenado) = 12 THEN 'Diciembre' END AS mes_letras FROM Tanqueo t INNER JOIN Ruta r ON t.id_ruta = r.id_ruta INNER JOIN Usuario u ON u.id_usuario = r.id_usuario WHERE u.id_usuario = ? AND YEAR(fecha_llenado) = YEAR(GETDATE()) GROUP BY MONTH(fecha_llenado) ORDER BY MONTH(fecha_llenado);");
            ps.setString(1, id_usuario);
            rs = ps.executeQuery();
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            while(rs.next()){
                dataset.setValue(rs.getDouble(1), "Soles", rs.getString(2));
            }
        
        JFreeChart linechart =ChartFactory.createLineChart("Ahorro por mes","Mes", "Soles", dataset, PlotOrientation.VERTICAL, true, true, true);
        
        CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();
        lineCategoryPlot.setBackgroundPaint(Color.white);
        
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
        Color lineChartColor = new Color(204,0,51);
        lineRenderer.setSeriesPaint(0, lineChartColor);
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        panelLineChart.removeAll();
        panelLineChart.add(lineChartPanel, BorderLayout.CENTER);
        panelLineChart.validate();
            
        } catch (Exception e) {
            System.out.println("Error al obtener el ahorro por mes: "+e.getMessage());
        }
    }

    public void showLineChart1(){
        Controlador_Ruta ruta = new Controlador_Ruta();
        Coneccion c = new Coneccion();
        Connection con = c.getConectar();
        ResultSet rs = null;
        PreparedStatement ps= null;
        try {
            ps=con.prepareStatement("select r.nombre_ruta from Ruta r INNER JOIN Tanqueo t on r.id_ruta=t.id_ruta INNER JOIN Vehiculo v on t.id_vehiculo=v.id_vehiculo INNER JOIN Asignacion a on a.id_vehiculo=v.id_vehiculo where a.id_usuario=? and CONCAT(v.marca, ' ', v.modelo) =? ;");
            ps.setString(1, id_usuario);
            ps.setString(2, vehiculo);
            rs = ps.executeQuery();
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            while(rs.next()){
                dataset.setValue(ruta.cantidadHaConsumir(id_usuario, vehiculo, rs.getString(1)), "Galones", rs.getString(1));
            }
        
        JFreeChart linechart =ChartFactory.createLineChart("Consumo por ruta","Ruta", "Galones", dataset, PlotOrientation.VERTICAL, true, true, true);
        
        CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();
        lineCategoryPlot.setBackgroundPaint(Color.white);
        
        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
        Color lineChartColor = new Color(204,0,51);
        lineRenderer.setSeriesPaint(0, lineChartColor);
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        panelLineChart.removeAll();
        panelLineChart.add(lineChartPanel, BorderLayout.CENTER);
        panelLineChart.validate();
            
        } catch (Exception e) {
            System.out.println("Error al obtener el ahorro por mes: "+e.getMessage());
        }
    }
}


