/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Coneccion.Coneccion;
import Controlador.Controlador_Tanqueo;
import Controlador.Controlador_Vehiculo;
import Daos.TanqueoDAO;
import Modelo.Tanqueo;
import Modelo.Vehiculo;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DateFormatSymbols;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;



/**
 *
 * @author Arice
 */
public final class Frame_Tanqueo extends javax.swing.JFrame {
    DefaultTableModel dt=new DefaultTableModel();
    Controlador_Tanqueo controller = new Controlador_Tanqueo();
    Controlador_Vehiculo controlador=new Controlador_Vehiculo();
    public static String correo;
    public static String id_usuario;
    public static String id_vehiculo;
    public static String id_ruta;
    public static String tipo;
    
    SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
    Calendar  fecha_actual=new GregorianCalendar();
    DateFormat formateador= new SimpleDateFormat("dd/MM/yyyy");
    SimpleDateFormat sdf = new SimpleDateFormat("EEEE", new Locale("es", "ES"));
    DateFormatSymbols dfs = new DateFormatSymbols(new Locale("es"));
    SimpleDateFormat formatoHora = new SimpleDateFormat("hh:mm a");
    /**
     * Creates new form Frame_Tanqueo
     */
    public Frame_Tanqueo() {
        initComponents();
        setIconImage(getIconImage());
        this.setLocationRelativeTo(null);
        this.setExtendedState(6);
        dt =(DefaultTableModel)jTablaTanque.getModel();
        jDateChooserFecha.setCalendar(fecha_actual);
        listarTanqueos();
        showPieChart();
        llenar_combobox();
        showPiePanel();
        cargar_grifos();        
    }
     @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Frame.png"));
        return retValue;
    }
    
    private void llenar_combobox(){
            cbVehiculo.removeAllItems();
            cbGrifo.addItem("Vehiculo");
            for (Vehiculo vehiculo : controlador.datos_generales_vehiculo(correo)) {
                cbVehiculo.addItem(vehiculo.getMarca()+" "+vehiculo.getModelo()); // Agregar el atributo deseado al modelo
            }
    }
    
    
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnAñadir = new Vista.PanelRound();
        jLabel33 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Logout = new Vista.PanelRound();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panelRound7 = new Vista.PanelRound();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panelRound9 = new Vista.PanelRound();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablaTanque = new javax.swing.JTable();
        panelRound16 = new Vista.PanelRound();
        cbGrifo = new javax.swing.JComboBox<>();
        jLabel43 = new javax.swing.JLabel();
        panelRound15 = new Vista.PanelRound();
        cbVehiculo = new javax.swing.JComboBox<>();
        jLabel42 = new javax.swing.JLabel();
        cant = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jDateChooserFecha = new com.toedter.calendar.JDateChooser();
        monto = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelRound14 = new Vista.PanelRound();
        panelBarChart = new javax.swing.JPanel();
        panelRound2 = new Vista.PanelRound();
        panelRound6 = new Vista.PanelRound();
        panelII = new javax.swing.JPanel();
        panelRound5 = new Vista.PanelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Nuevo Tanqueo");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        btnAñadir.setBackground(new java.awt.Color(0, 106, 255));
        btnAñadir.setRoundBottomLeft(10);
        btnAñadir.setRoundBottomRight(10);
        btnAñadir.setRoundTopLeft(10);
        btnAñadir.setRoundTopRight(10);
        btnAñadir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAñadirMouseClicked(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(242, 242, 242));
        jLabel33.setText("Añadir");
        jLabel33.setAlignmentY(0.0F);

        javax.swing.GroupLayout btnAñadirLayout = new javax.swing.GroupLayout(btnAñadir);
        btnAñadir.setLayout(btnAñadirLayout);
        btnAñadirLayout.setHorizontalGroup(
            btnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAñadirLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnAñadirLayout.setVerticalGroup(
            btnAñadirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnAñadirLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 70, 121, 40));

        jPanel3.setBackground(new java.awt.Color(26, 25, 25));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Group 10.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 35, 170, 70));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        Logout.setBackground(new java.awt.Color(47, 47, 47));
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setRoundBottomLeft(10);
        Logout.setRoundBottomRight(10);
        Logout.setRoundTopLeft(10);
        Logout.setRoundTopRight(10);
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LogoutMouseClicked(evt);
            }
        });
        Logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logout.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        Logout.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 15, 20, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/placeholder.png"))); // NOI18N
        Logout.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jPanel3.add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 610, 150, 50));

        panelRound7.setBackground(new java.awt.Color(0, 106, 255));
        panelRound7.setForeground(new java.awt.Color(255, 255, 255));
        panelRound7.setRoundBottomLeft(10);
        panelRound7.setRoundBottomRight(10);
        panelRound7.setRoundTopLeft(10);
        panelRound7.setRoundTopRight(10);
        panelRound7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRound7MouseClicked(evt);
            }
        });
        panelRound7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tanqueos");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        panelRound7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 13, 80, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Payment.png"))); // NOI18N
        panelRound7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 13, -1, -1));

        panelRound9.setBackground(new java.awt.Color(255, 255, 255));
        panelRound9.setForeground(new java.awt.Color(255, 255, 255));
        panelRound9.setRoundBottomLeft(5);
        panelRound9.setRoundBottomRight(5);
        panelRound9.setRoundTopLeft(5);
        panelRound9.setRoundTopRight(5);
        panelRound9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panelRound7.add(panelRound9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 5, 40));

        jPanel3.add(panelRound7, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 390, 180, 50));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu (3).png"))); // NOI18N
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 450, 180, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu (1).png"))); // NOI18N
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 180, 180, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Header.png"))); // NOI18N
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 330, 180, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu (4).png"))); // NOI18N
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 240, 180, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Split line.png"))); // NOI18N
        jLabel20.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 190, -1));

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Menu.png"))); // NOI18N
        jLabel37.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel37.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel37.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel37MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 180, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        jScrollPane1.setBorder(null);

        jTablaTanque.setAutoCreateRowSorter(true);
        jTablaTanque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nro", "Vehiculo", "Lugar", "Cantidad", "Monto", "Fecha"
            }
        ));
        jTablaTanque.setFillsViewportHeight(true);
        jTablaTanque.setFocusCycleRoot(true);
        jTablaTanque.setGridColor(new java.awt.Color(255, 255, 255));
        jTablaTanque.setSelectionBackground(new java.awt.Color(102, 153, 255));
        jTablaTanque.setShowVerticalLines(true);
        jScrollPane1.setViewportView(jTablaTanque);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 1010, 140));

        panelRound16.setBackground(new java.awt.Color(255, 255, 255));
        panelRound16.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound16.setRoundBottomLeft(10);
        panelRound16.setRoundBottomRight(10);
        panelRound16.setRoundTopLeft(10);
        panelRound16.setRoundTopRight(10);

        cbGrifo.setEditable(true);
        cbGrifo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grifo", "Item 2", "Item 3", "Item 4" }));
        cbGrifo.setToolTipText("");
        cbGrifo.setBorder(null);
        cbGrifo.setFocusable(false);
        cbGrifo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrifoActionPerformed(evt);
            }
        });

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icon _pin alt_.png"))); // NOI18N

        javax.swing.GroupLayout panelRound16Layout = new javax.swing.GroupLayout(panelRound16);
        panelRound16.setLayout(panelRound16Layout);
        panelRound16Layout.setHorizontalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound16Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbGrifo, 0, 103, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        panelRound16Layout.setVerticalGroup(
            panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound16Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelRound16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel43)
                    .addComponent(cbGrifo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelRound16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 170, 40));

        panelRound15.setBackground(new java.awt.Color(255, 255, 255));
        panelRound15.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelRound15.setRoundBottomLeft(10);
        panelRound15.setRoundBottomRight(10);
        panelRound15.setRoundTopLeft(10);
        panelRound15.setRoundTopRight(10);

        cbVehiculo.setEditable(true);
        cbVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbVehiculo.setToolTipText("");
        cbVehiculo.setBorder(null);
        cbVehiculo.setFocusable(false);
        cbVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbVehiculoItemStateChanged(evt);
            }
        });
        cbVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVehiculoActionPerformed(evt);
            }
        });

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/bx_car.png"))); // NOI18N

        javax.swing.GroupLayout panelRound15Layout = new javax.swing.GroupLayout(panelRound15);
        panelRound15.setLayout(panelRound15Layout);
        panelRound15Layout.setHorizontalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound15Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbVehiculo, 0, 106, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );
        panelRound15Layout.setVerticalGroup(
            panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound15Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(panelRound15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel42)
                    .addComponent(cbVehiculo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(panelRound15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 160, 40));

        cant.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        cant.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.add(cant, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 70, 80, 40));

        jLabel10.setText("Gal");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 70, 20, 40));

        jDateChooserFecha.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jDateChooserFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 70, 150, 40));

        monto.setText("Monto Pagado");
        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        jPanel2.add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 140, 40));

        jLabel35.setText("Historial de Tanqueos");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Graph1.png"))); // NOI18N
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 1120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Live Car Status1.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, -1, -1));

        panelRound14.setBackground(new java.awt.Color(255, 255, 255));
        panelRound14.setRoundBottomLeft(30);
        panelRound14.setRoundBottomRight(30);
        panelRound14.setRoundTopLeft(30);
        panelRound14.setRoundTopRight(30);
        panelRound14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarChart.setBackground(new java.awt.Color(255, 255, 255));
        panelBarChart.setLayout(new java.awt.BorderLayout());
        panelRound14.add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 360, 220));

        jPanel2.add(panelRound14, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 405, 400, 260));

        panelRound2.setBackground(new java.awt.Color(163, 163, 163, 100));
        panelRound2.setPreferredSize(new java.awt.Dimension(290, 120));
        panelRound2.setRequestFocusEnabled(false);
        panelRound2.setRoundBottomLeft(30);
        panelRound2.setRoundBottomRight(30);
        panelRound2.setRoundTopLeft(30);
        panelRound2.setRoundTopRight(30);
        panelRound2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(panelRound2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 400, 410, 270));

        panelRound6.setBackground(new java.awt.Color(255, 255, 255));
        panelRound6.setRoundBottomLeft(30);
        panelRound6.setRoundBottomRight(30);
        panelRound6.setRoundTopLeft(30);
        panelRound6.setRoundTopRight(30);
        panelRound6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelII.setBackground(new java.awt.Color(255, 255, 255));
        panelII.setLayout(new java.awt.BorderLayout());
        panelRound6.add(panelII, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 370, 220));

        jPanel2.add(panelRound6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 405, 410, 260));

        panelRound5.setBackground(new java.awt.Color(163, 163, 163, 100));
        panelRound5.setPreferredSize(new java.awt.Dimension(290, 120));
        panelRound5.setRequestFocusEnabled(false);
        panelRound5.setRoundBottomLeft(30);
        panelRound5.setRoundBottomRight(30);
        panelRound5.setRoundTopLeft(30);
        panelRound5.setRoundTopRight(30);
        panelRound5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(panelRound5, new org.netbeans.lib.awtextra.AbsoluteConstraints(795, 400, 420, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVehiculoActionPerformed

    private void cbGrifoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrifoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGrifoActionPerformed

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        if (monto.getText().equals("Monto Pagado")){
            monto.setText("");
            monto.setForeground(Color.black);
        }
        
    }//GEN-LAST:event_montoActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        this.setVisible(false);
        Frame_Reportes reporte = new  Frame_Reportes();
        reporte.setLocationRelativeTo(null);
        reporte.setVisible(true);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void panelRound7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRound7MouseClicked
       this.setVisible(false);
        Frame_Tanqueo tanqueo = new  Frame_Tanqueo();
        tanqueo.setLocationRelativeTo(null);
        tanqueo.setVisible(true);
    }//GEN-LAST:event_panelRound7MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setVisible(false);
        Frame_Ruta ruta = new  Frame_Ruta();
        ruta.setLocationRelativeTo(null);
        ruta.setVisible(true);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
       this.setVisible(false);
        Frame_Vehiculo vehiculo = new  Frame_Vehiculo();
        vehiculo.setLocationRelativeTo(null);
        vehiculo.setVisible(true);
    }//GEN-LAST:event_jLabel12MouseClicked

    private void jLabel37MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel37MouseClicked
        this.setVisible(false);
        Frame_Inicio inicio = new  Frame_Inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_jLabel37MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.setVisible(false);
        Frame_Inicio inicio = new  Frame_Inicio();
        inicio.setLocationRelativeTo(null);
        inicio.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void cbVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbVehiculoItemStateChanged
        String vehiculo = (String) cbVehiculo.getSelectedItem();
        id_vehiculo=controlador.idvehiculo(vehiculo);
        listarTanqueos();
        Frame_Reportes.id_vehiculo = id_vehiculo;
    }//GEN-LAST:event_cbVehiculoItemStateChanged

    private void btnAñadirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAñadirMouseClicked
        System.out.println("vehiculo: "+id_vehiculo);
        System.out.println("ruta : "+id_ruta);
        System.out.println("pago: "+monto.getText());
        System.out.println("cantida: "+cant.getValue().toString());
        String fecha =""+formatoFecha.format(jDateChooserFecha.getDate());
        controller.añadirTanqueo(id_vehiculo, id_ruta,cbGrifo.getSelectedItem().toString() , monto.getText(),fecha , cant.getValue().toString());
        listarTanqueos();  
        
        
    }//GEN-LAST:event_btnAñadirMouseClicked

    private void LogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMouseClicked
        this.setVisible(false);
        Frame_usuario usu = new  Frame_usuario();
        usu.setLocationRelativeTo(null);
        usu.setVisible(true);
    }//GEN-LAST:event_LogoutMouseClicked
    private void cargar_grifos(){
        cbGrifo.removeAllItems();
        cbGrifo.addItem("Grifo");
        for (Tanqueo tanqueo : controller.ListGrifo()) {
            cbGrifo.addItem(tanqueo.getLugar()); // Agregar el atributo deseado al modelo
        }
    }
    private void listarTanqueos() {         
        dt.setRowCount(0);
        for(Tanqueo tanqueo:controller.listarTanqueos(id_usuario, id_vehiculo)){
            Object v[]={
                tanqueo.getCodTanqueo(), 
                tanqueo.getVehiculo().getCodVehiculo(), 
                tanqueo.getLugar(), 
                tanqueo.getCantLlenada(), 
                tanqueo.getPagoTotal(),  
                tanqueo.getFecha()};
            dt.addRow(v);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Tanqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Tanqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Tanqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Tanqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Tanqueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Vista.PanelRound Logout;
    private Vista.PanelRound btnAñadir;
    private javax.swing.JSpinner cant;
    private javax.swing.JComboBox<String> cbGrifo;
    private javax.swing.JComboBox<String> cbVehiculo;
    private com.toedter.calendar.JDateChooser jDateChooserFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablaTanque;
    private javax.swing.JTextField monto;
    private javax.swing.JPanel panelBarChart;
    private javax.swing.JPanel panelII;
    private Vista.PanelRound panelRound14;
    private Vista.PanelRound panelRound15;
    private Vista.PanelRound panelRound16;
    private Vista.PanelRound panelRound2;
    private Vista.PanelRound panelRound5;
    private Vista.PanelRound panelRound6;
    private Vista.PanelRound panelRound7;
    private Vista.PanelRound panelRound9;
    // End of variables declaration//GEN-END:variables
    public void showPieChart(){
        Coneccion c = new Coneccion();
        Connection con = c.getConectar();
        ResultSet rs = null;
        PreparedStatement ps= null;
        try {
            ps=con.prepareStatement("SELECT t.lugar_llenado, COUNT(*) AS repeticiones FROM Tanqueo t INNER JOIN Ruta r ON r.id_ruta = t.id_ruta WHERE r.id_usuario =? AND t.lugar_llenado <>'no' GROUP BY t.lugar_llenado HAVING COUNT(*) >= 1 ORDER BY repeticiones DESC");
            ps.setString(1, id_usuario);
            rs = ps.executeQuery();
            DefaultPieDataset barDataset = new DefaultPieDataset();
            while(rs.next()){
                barDataset.setValue(rs.getString(1), rs.getDouble(2));
            }
             //create chart
        JFreeChart piechart =ChartFactory.createPieChart("Tanqueo por grifo",barDataset, true, true, false);
        PiePlot piePlot =(PiePlot) piechart.getPlot();
     //changing pie chart blocks colors
        piePlot.setBackgroundPaint (Color. white);
        piePlot.setOutlinePaint(Color. white);
        piePlot.setLabelOutlinePaint(Color. white);
        piePlot.setBaseSectionPaint(Color. white);
       //create chartPanel to display chart (gcaph)
       ChartPanel barChartPanel = new ChartPanel (piechart);
       panelBarChart.removeAll();
       panelBarChart.add(barChartPanel, BorderLayout.CENTER);
       panelBarChart.validate();
        } catch (Exception e) {
            System.out.println("Error al obtener los grifos: "+e.getMessage());
        }        
    }
    public void showPiePanel() {        
        
        DefaultPieDataset barDataset = new DefaultPieDataset();
        barDataset.setValue("Ahorro", controller.ahorroanio(id_usuario));
        barDataset.setValue("Gasto", controller.ahorrogasto(id_usuario));
        //create chart
        JFreeChart piechart =ChartFactory.createPieChart("Ahorro vs Gastos",barDataset, true, true, false);
        
        PiePlot piePlot =(PiePlot) piechart.getPlot();
     //changing pie chart blocks colors
        piePlot.setSectionPaint("Ahorro", new Color (10,204, 204));
        piePlot.setSectionPaint ("Gasto", new Color(102, 255, 102));
        piePlot.setBackgroundPaint (Color. white);
        piePlot.setOutlinePaint(Color. white);
        piePlot.setLabelOutlinePaint(Color. white);
        piePlot.setBaseSectionPaint(Color. white);
       //create chartPanel to display chart (gcaph)
       ChartPanel barChartPanel = new ChartPanel (piechart);
       panelII.removeAll();
       panelII.add(barChartPanel, BorderLayout.CENTER);
       panelII.validate();

    }
}
